[package]
name = "status-page-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventsource = "0.5.0"
reqwest = "0.11.18"
